# -*- coding: utf-8 -*-
"""YOLOv7 on custom data

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12JL2RXM7toza_iXRZM951-ed_0JCtZoL
"""

import torch
import os
from IPython.display import Image, clear_output

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/WongKinYiu/yolov7
# %cd yolov7
!pip install -r requirements.txt

!pip install roboflow
from roboflow import Roboflow
rf = Roboflow(api_key="E9ecyBX8LYTK9mmEkB8X")
project = rf.workspace("fffff-m2css").project("ff-ucc3i")
dataset = project.version(2).download("yolov7")

os.environ["DATASET_DIRECTORY"] = "/content/yolov7/ff-2"

!python train.py --batch 16 --img 640 --epochs 100 --data {dataset.location}/data.yaml --weights '' --cfg /content/yolov7/cfg/training/yolov7.yaml --device 0 --cache

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir runs

!python detect.py --weights runs/train/exp/weights/best.pt --conf 0.1 --source {dataset.location}/test/images

import matplotlib.pyplot as plt
import numpy as np

class_names = ['ukupno', 'osoba', 'sportska lopta']
metrics = ['P', 'R', 'mAP50', 'mAP50-95']
data = [
    [0.737, 0.867, 0.608],
    [0.541, 0.883, 0.199],
    [0.56, 0.916, 0.204],
    [0.249, 0.398, 0.0999]
]


fig, ax = plt.subplots()
bar_width = 0.15
opacity = 0.8

for i in range(len(metrics)):
    pos = [j + i * bar_width for j in range(len(class_names))]
    ax.bar(pos, data[i], bar_width, alpha=0.8, label=metrics[i])
ax.set_xlabel('klasa')
ax.set_ylabel('rezultat')
ax.set_title('Rezultati YOLOv7')
ax.set_xticks([r + bar_width*2 for r in range(len(class_names))])
ax.set_xticklabels(class_names)
ax.legend(bbox_to_anchor=(1, 0.4))

ax.yaxis.grid(color='gray', linestyle='dashed', alpha=0.4)

plt.show()
#yolov7